### ISSUE TITLE
DEVELOPER STORY: Manufacturer DB Table

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/TechCore#20]
As a **developer**, I want **to have a database table to store product's manufacturers** so that **user can filter products by manufacturers**.

## Acceptance Criteria
1. Create necessary field (name).
2. Set a unique constraint for the **name** fields.
3. Add additional fields as needed.

**Comment by aleroldan156** [comment]
maybe this will help

https://bit.ly/4eugCty

you may need to install the c compiler
